# 开源自动化测试工具

## Selenium

[官网地址](https://www.selenium.dev)

网址：https://www.selenium.dev

中文文档地址：https://selenium-python-zh.readthedocs.io/en/latest/index.html

中文文档地址2：https://wizardforcel.gitbooks.io/selenium-doc/content/official-site/introduction.html

### 简介

一款开源的web自动化测试工具，支持分布式，支持java，js，python等语言，支持市面上几乎所有的浏览器，并且在所有支持这些浏览器的系统中都运行良好。

不支持非web项目

## Appium

### 简介

1. appium是开源的移动端自动化测试框架；

2. appium可以测试原生的、混合的、以及移动端的web项目；

3. appium可以测试ios，android应用（还有firefox os）

4. appium是跨平台的，可以用在osx，windows以及linux桌面系统上；

5. appium支持多种语言Ruby、Python、Java、JavaScript、Objective C、php、C#、RobotFramework

### 官网和参考文档

官网：http://appium.io

官网文档：http://appium.io/docs/en/about-appium/intro/

官方中文文档：http://appium.io/docs/cn/about-appium/intro/

知乎上的简介：https://zhuanlan.zhihu.com/p/61971173

## Flutter Integration Tests

### 官网和参考文档

package地址:https://pub.dev/packages/integration_test

github地址：https://github.com/flutter/plugins/tree/master/packages/integration_test

flutter中文资源站：https://flutter.cn/docs/testing/integration-tests

使用`integration_test`包结合`flutter_test`的单元测试和Widgets测试，对函数和Widget编写测试用例，然后使用`flutter_driver`的 `flutter driver`命令运行这些测试样例

### 使用

- 在yaml文件的dev_dependencies下添加

  ```yaml
  dev_dependencies:
  
    #flutter 单元测试和Widgets测试
    flutter_test:
      sdk: flutter
    #flutter 集成测试
    integration_test: ^1.0.0
    flutter_driver:
      sdk: flutter
  ```

- 项目根目录下添加`integration_test`目录和`xx_test.dart`文件

  ```dart
  ///xx_test.dart文件内容
  import 'package:flutter_test/flutter_test.dart';
  import 'package:integration_test/integration_test.dart';
  
  void main(){
    ///初始化
    IntegrationTestWidgetsFlutterBinding.ensureInitialized();
  
    testWidgets('test====', (WidgetTester tester)async{
       expect(2 + 2, equals(4));
      ///启动MyApp  widget，pumpWidget后不会再次刷新widget，除非  
      await tester.pumpWidget(MyApp());
  
      // Verify that our counter starts at 0.
      ///验证text widget的起始值是否为0
      ///find是辅助查找目标Widget的类和验证widget是否正常工作的类
      expect(find.text('0'), findsOneWidget);
      expect(find.text('1'), findsNothing);
      ///模拟add icon的点击事件
      // Tap the '+' icon and trigger a frame.
      for (int i = 0; i < 30; i++) {
        await tester.tap(find.byIcon(Icons.add));
  
        ///重建Widget(即刷新页面)
        await tester.pump(const Duration(milliseconds: 500));
        expect(find.text('${i +1}'), findsOneWidget);
      }
      // Verify that our counter has incremented.
      ///
      expect(find.text('0'), findsNothing);
      expect(find.text('1'), findsOneWidget);
    });
  }
  ```

- 使用`flutter_driver`命令运行程序

  - 项目根目录下添加`test_driver`文件夹和`integration_test_driver.dart`文件

    ```dart
    ///`integration_test_driver.dart`文件内容
    import 'package:integration_test/integration_test_driver_extended.dart';
    
    ///flutter driver命令运行的main方法
    Future<void> main() {
      return integrationDriver();
    }
    ```

    

  - 在终端执行如下命令在真机/模拟器中运行测试

    ```shell
    flutter driver --driver=test_driver/integration_test_driver.dart --target=integration_test/demo_test.dart
    ```

  - 测试结果

    测试通过的结果

    ```shell
    $>>> flutter driver --driver=test_driver/integration_test_driver.dart --target=integration_test/demo_test.dart
    Using device EVR AL00.
    Starting application: integration_test/demo_test.dart
    "build/app/outputs/flutter-apk/app.apk" does not exist.
    Running Gradle task 'assembleDebug'...                                  
    Running Gradle task 'assembleDebug'... Done                        33.3s
    ✓ Built build/app/outputs/flutter-apk/app-debug.apk.
    Installing build/app/outputs/flutter-apk/app.apk...                10.1s
    I/flutter (24738): Observatory listening on http://127.0.0.1:39839/dMaCVohstJ4=/
    VMServiceFlutterDriver: Connecting to Flutter application at http://127.0.0.1:60777/dMaCVohstJ4=/
    VMServiceFlutterDriver: Isolate found with number: 1021301541835079
    VMServiceFlutterDriver: Isolate is paused at start.
    VMServiceFlutterDriver: Attempting to resume isolate
    I/flutter (24738): 00:00 +0: test====
    VMServiceFlutterDriver: Connected to Flutter application.
    I/flutter (24738): 00:00 +1: (tearDownAll)
    I/flutter (24738): 00:00 +2: All tests passed!
    All tests passed.
    Stopping application instance.
    ```

    含有测试失败项的结果：

    ```shell
    $>>> flutter driver --driver=test_driver/integration_test_driver.dart --target=integration_test/demo_test.dart
    Using device EVR AL00.
    Starting application: integration_test/demo_test.dart
    Installing build/app/outputs/flutter-apk/app.apk...                 6.0s
    Running Gradle task 'assembleDebug'...                                  
    Running Gradle task 'assembleDebug'... Done                        13.9s
    ✓ Built build/app/outputs/flutter-apk/app-debug.apk.
    I/flutter (26295): Observatory listening on http://127.0.0.1:39077/K34itROO7Lo=/
    I/flutter (26295): 00:00 +0: test====                                   
    I/flutter (26295): 00:00 +1: (tearDownAll)                              
    I/flutter (26295): 00:00 +2: All tests passed!                          
    Installing build/app/outputs/flutter-apk/app.apk...                10.9s
    I/flutter (26494): Observatory listening on http://127.0.0.1:33961/sVRk9n0QwpI=/
    VMServiceFlutterDriver: Connecting to Flutter application at http://127.0.0.1:61577/sVRk9n0QwpI=/
    VMServiceFlutterDriver: Isolate found with number: 2745649757703519
    VMServiceFlutterDriver: Isolate is paused at start.
    VMServiceFlutterDriver: Attempting to resume isolate
    I/flutter (26494): 00:00 +0: test====
    VMServiceFlutterDriver: Connected to Flutter application.
    I/flutter (26494): (The following exception is now available via WidgetTester.takeException:)
    I/flutter (26494): ══╡ EXCEPTION CAUGHT BY FLUTTER TEST FRAMEWORK ╞════════════════════════════════════════════════════
    I/flutter (26494): The following TestFailure object was thrown running a test:
    I/flutter (26494):   Expected: <5>
    I/flutter (26494):   Actual: <4>
    I/flutter (26494): 
    I/flutter (26494): When the exception was thrown, this was the stack:
    I/flutter (26494): #4      main.<anonymous closure>
    (file:///Users/cheng/flutter/projects/UnitTestDemo/integration_test/demo_test.dart:9:5)
    I/flutter (26494): #5      testWidgets.<anonymous closure>.<anonymous closure>
    (package:flutter_test/src/widget_tester.dart:146:29)
    I/flutter (26494): <asynchronous suspension>
    I/flutter (26494): #6      testWidgets.<anonymous closure>.<anonymous closure>
    (package:flutter_test/src/widget_tester.dart)
    I/flutter (26494): #7      TestWidgetsFlutterBinding._runTestBody (package:flutter_test/src/binding.dart:784:19)
    I/flutter (26494): <asynchronous suspension>
    I/flutter (26494): #10     TestWidgetsFlutterBinding._runTest (package:flutter_test/src/binding.dart:764:14)
    I/flutter (26494): #11     LiveTestWidgetsFlutterBinding.runTest (package:flutter_test/src/binding.dart:1592:12)
    I/flutter (26494): #12     IntegrationTestWidgetsFlutterBinding.runTest
    (package:integration_test/integration_test.dart:194:17)
    I/flutter (26494): #13     testWidgets.<anonymous closure> (package:flutter_test/src/widget_tester.dart:138:24)
    I/flutter (26494): #14     Declarer.test.<anonymous closure>.<anonymous closure>
    (package:test_api/src/backend/declarer.dart:175:19)
    I/flutter (26494): <asynchronous suspension>
    I/flutter (26494): #15     Declarer.test.<anonymous closure>.<anonymous closure>
    (package:test_api/src/backend/declarer.dart)
    I/flutter (26494): #20     Declarer.test.<anonymous closure> (package:test_api/src/backend/declarer.dart:173:13)
    I/flutter (26494): #21     Invoker.waitForOutstandingCallbacks.<anonymous closure>
    (package:test_api/src/backend/invoker.dart:231:15)
    I/flutter (26494): #26     Invoker.waitForOutstandingCallbacks (package:test_api/src/backend/invoker.dart:228:5)
    I/flutter (26494): #27     Invoker._onRun.<anonymous closure>.<anonymous closure>.<anonymous closure>
    (package:test_api/src/backend/invoker.dart:383:17)
    I/flutter (26494): <asynchronous suspension>
    I/flutter (26494): #28     Invoker._onRun.<anonymous closure>.<anonymous closure>.<anonymous closure>
    (package:test_api/src/backend/invoker.dart)
    I/flutter (26494): #33     Invoker._onRun.<anonymous closure>.<anonymous closure>
    (package:test_api/src/backend/invoker.dart:370:9)
    I/flutter (26494): #34     Invoker._guardIfGuarded (package:test_api/src/backend/invoker.dart:415:15)
    I/flutter (26494): #35     Invoker._onRun.<anonymous closure> (package:test_api/src/backend/invoker.dart:369:7)
    I/flutter (26494): #42     Invoker._onRun (package:test_api/src/backend/invoker.dart:368:11)
    I/flutter (26494): #43     LiveTestController.run (package:test_api/src/backend/live_test_controller.dart:153:11)
    I/flutter (26494): (elided 31 frames from dart:async and package:stack_trace)
    I/flutter (26494): 
    I/flutter (26494): This was caught by the test expectation on the following line:
    I/flutter (26494):   file:///Users/cheng/flutter/projects/UnitTestDemo/integration_test/demo_test.dart line 9
    I/flutter (26494): The test description was:
    I/flutter (26494):   test====
    I/flutter (26494): ════════════════════════════════════════════════════════════════════════════════════════════════════
    I/flutter (26494): (If WidgetTester.takeException is called, the above exception will be ignored. If it is not, then the
    above exception will be dumped when another exception is caught by the framework or when the test ends, whichever happens
    first, and then the test will fail due to having not caught or expected the exception.)
    I/flutter (26494): ══╡ EXCEPTION CAUGHT BY FLUTTER TEST FRAMEWORK ╞════════════════════════════════════════════════════
    I/flutter (26494): The following TestFailure object was thrown running a test:
    I/flutter (26494):   Expected: <5>
    I/flutter (26494):   Actual: <4>
    I/flutter (26494): 
    I/flutter (26494): When the exception was thrown, this was the stack:
    I/flutter (26494): #4      main.<anonymous closure>
    (file:///Users/cheng/flutter/projects/UnitTestDemo/integration_test/demo_test.dart:9:5)
    I/flutter (26494): #5      testWidgets.<anonymous closure>.<anonymous closure>
    (package:flutter_test/src/widget_tester.dart:146:29)
    I/flutter (26494): <asynchronous suspension>
    I/flutter (26494): #6      testWidgets.<anonymous closure>.<anonymous closure>
    (package:flutter_test/src/widget_tester.dart)
    I/flutter (26494): #7      TestWidgetsFlutterBinding._runTestBody (package:flutter_test/src/binding.dart:784:19)
    I/flutter (26494): <asynchronous suspension>
    I/flutter (26494): #10     TestWidgetsFlutterBinding._runTest (package:flutter_test/src/binding.dart:764:14)
    I/flutter (26494): #11     LiveTestWidgetsFlutterBinding.runTest (package:flutter_test/src/binding.dart:1592:12)
    I/flutter (26494): #12     IntegrationTestWidgetsFlutterBinding.runTest
    (package:integration_test/integration_test.dart:194:17)
    I/flutter (26494): #13     testWidgets.<anonymous closure> (package:flutter_test/src/widget_tester.dart:138:24)
    I/flutter (26494): #14     Declarer.test.<anonymous closure>.<anonymous closure>
    (package:test_api/src/backend/declarer.dart:175:19)
    I/flutter (26494): <asynchronous suspension>
    I/flutter (26494): #15     Declarer.test.<anonymous closure>.<anonymous closure>
    (package:test_api/src/backend/declarer.dart)
    I/flutter (26494): #20     Declarer.test.<anonymous closure> (package:test_api/src/backend/declarer.dart:173:13)
    I/flutter (26494): #21     Invoker.waitForOutstandingCallbacks.<anonymous closure>
    (package:test_api/src/backend/invoker.dart:231:15)
    I/flutter (26494): #26     Invoker.waitForOutstandingCallbacks (package:test_api/src/backend/invoker.dart:228:5)
    I/flutter (26494): #27     Invoker._onRun.<anonymous closure>.<anonymous closure>.<anonymous closure>
    (package:test_api/src/backend/invoker.dart:383:17)
    I/flutter (26494): <asynchronous suspension>
    I/flutter (26494): #28     Invoker._onRun.<anonymous closure>.<anonymous closure>.<anonymous closure>
    (package:test_api/src/backend/invoker.dart)
    I/flutter (26494): #33     Invoker._onRun.<anonymous closure>.<anonymous closure>
    (package:test_api/src/backend/invoker.dart:370:9)
    I/flutter (26494): #34     Invoker._guardIfGuarded (package:test_api/src/backend/invoker.dart:415:15)
    I/flutter (26494): #35     Invoker._onRun.<anonymous closure> (package:test_api/src/backend/invoker.dart:369:7)
    I/flutter (26494): #42     Invoker._onRun (package:test_api/src/backend/invoker.dart:368:11)
    I/flutter (26494): #43     LiveTestController.run (package:test_api/src/backend/live_test_controller.dart:153:11)
    I/flutter (26494): (elided 31 frames from dart:async and package:stack_trace)
    I/flutter (26494): 
    I/flutter (26494): This was caught by the test expectation on the following line:
    I/flutter (26494):   file:///Users/cheng/flutter/projects/UnitTestDemo/integration_test/demo_test.dart line 9
    I/flutter (26494): The test description was:
    I/flutter (26494):   test====
    I/flutter (26494): ════════════════════════════════════════════════════════════════════════════════════════════════════
    I/flutter (26494): 00:00 +0: test==== [E]
    I/flutter (26494):   Test failed. See exception logs above.
    I/flutter (26494):   The test description was: test====
    I/flutter (26494):   
    I/flutter (26494): 00:00 +0 -1: (tearDownAll)
    Failure Details:
    Failure in method: test====
    ══╡ EXCEPTION CAUGHT BY FLUTTER TEST FRAMEWORK ╞═════════════════
    The following TestFailure object was thrown running a test:
      Expected: <5>
      Actual: <4>
    
    When the exception was thrown, this was the stack:
    #4      main.<anonymous closure> (file:///Users/cheng/flutter/projects/UnitTestDemo/integration_test/demo_test.dart:9:5)
    #5      testWidgets.<anonymous closure>.<anonymous closure> (package:flutter_test/src/widget_tester.dart:146:29)
    <asynchronous suspension>
    #6      testWidgets.<anonymous closure>.<anonymous closure> (package:flutter_test/src/widget_tester.dart)
    #7      TestWidgetsFlutterBinding._runTestBody (package:flutter_test/src/binding.dart:784:19)
    <asynchronous suspension>
    #10     TestWidgetsFlutterBinding._runTest (package:flutter_test/src/binding.dart:764:14)
    #11     LiveTestWidgetsFlutterBinding.runTest (package:flutter_test/src/binding.dart:1592:12)
    #12     IntegrationTestWidgetsFlutterBinding.runTest (package:integration_test/integration_test.dart:194:17)
    #13     testWidgets.<anonymous closure> (package:flutter_test/src/widget_tester.dart:138:24)
    #14     Declarer.test.<anonymous closure>.<anonymous closure> (package:test_api/src/backend/declarer.dart:175:19)
    <asynchronous suspension>
    #15     Declarer.test.<anonymous closure>.<anonymous closure> (package:test_api/src/backend/declarer.dart)
    #20     Declarer.test.<anonymous closure> (package:test_api/src/backend/declarer.dart:173:13)
    #21     Invoker.waitForOutstandingCallbacks.<anonymous closure> (package:test_api/src/backend/invoker.dart:231:15)
    #26     Invoker.waitForOutstandingCallbacks (package:test_api/src/backend/invoker.dart:228:5)
    #27     Invoker._onRun.<anonymous closure>.<anonymous closure>.<anonymous closure> (package:test_api/src/backend/invoker.dart:383:17)
    <asynchronous suspension>
    #28     Invoker._onRun.<anonymous closure>.<anonymous closure>.<anonymous closure> (package:test_api/src/backend/invoker.dart)
    #33     Invoker._onRun.<anonymous closure>.<anonymous closure> (package:test_api/src/backend/invoker.dart:370:9)
    #34     Invoker._guardIfGuarded (package:test_api/src/backend/invoker.dart:415:15)
    #35     Invoker._onRun.<anonymous closure> (package:test_api/src/backend/invoker.dart:369:7)
    #42     Invoker._onRun (package:test_api/src/backend/invoker.dart:368:11)
    #43     LiveTestController.run (package:test_api/src/backend/live_test_controller.dart:153:11)
    (elided 31 frames from dart:async and package:stack_trace)
    
    This was caught by the test expectation on the following line:
      file:///Users/cheng/flutter/projects/UnitTestDemo/integration_test/demo_test.dart line 9
    The test description was:
      test====
    ═════════════════════════════════════════════════════════════════
    
    end of failure 1
    
    
    
    I/flutter (26494): 00:00 +1 -1: Some tests failed.
    Stopping application instance.
    Driver tests failed: 1
    
    ```

    

### 目录结构

```dart
lib/
  ...
integration_test/
  demo_test.dart
  other_test.dart
  ...
test/
  widget_test.dart
  ...
test_driver/
  integration_test_driver.dart
```



## 多个设备同时测试并输出log文件

- 使用`&`多线程运行。在每个命令后边添加`&`符号，既可以为其分配一个线程运行该命令

  ```shell
  flutter driver --driver=test_driver/integration_test_driver.dart --target=integration_test/demo_test.dart -d 837214AC-E0B1-4B32-A88D-34BF1F7694A3 &
  ```

- 使用`nohub`命令后台运行。在命令起始添加`nohub`即可使其后台运行，此时终端可以继续输入其他命令并执行

  ```shell
  nohup flutter driver --driver=test_driver/integration_test_driver.dart --target=integration_test/demo_test.dart -d 837214AC-E0B1-4B32-A88D-34BF1F7694A3 &
  ```

- 使用 `>`输出log到指定文件中

  ```shell
  nohup flutter driver --driver=test_driver/integration_test_driver.dart --target=integration_test/demo_test.dart -d 837214AC-E0B1-4B32-A88D-34BF1F7694A3 > log.txt &
  ```

  

- 使用`nohub`和`&`让多个设备同时进行测试

  ```shell
  nohup flutter driver --driver=test_driver/integration_test_driver.dart --target=integration_test/demo_test.dart -d 837214AC-E0B1-4B32-A88D-34BF1F7694A3 & nohup flutter driver --driver=test_driver/integration_test_driver.dart --target=integration_test/demo_test.dart -d LKN5T18B02013810 & 
  ```

- 使用`nohub`、`&`、`>` 让多设备同时输出log到指定文件

  ```shell
  nohup flutter driver --driver=test_driver/integration_test_driver.dart --target=integration_test/demo_test.dart -d 837214AC-E0B1-4B32-A88D-34BF1F7694A3 > 837214AC-E0B1-4B32-A88D-34BF1F7694A3log.txt & nohup flutter driver --driver=test_driver/integration_test_driver.dart --target=integration_test/demo_test.dart -d LKN5T18B02013810 > LKN5T18B02013810log.txt & 
  ```

  



